<org.uberfire.java.nio.base.Properties serialization="custom">
  <unserializable-parents/>
  <map>
    <default>
      <loadFactor>0.75</loadFactor>
      <threshold>12</threshold>
    </default>
    <int>16</int>
    <int>4</int>
    <string>dcore.relation[0]</string>
    <string></string>
    <string>dcore.subject[0]</string>
    <string></string>
    <string>dcore.description[0]</string>
    <string>&lt;imported&gt;</string>
    <string>dcore.source[0]</string>
    <string>Imported from external DRL</string>
  </map>
</org.uberfire.java.nio.base.Properties>